---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- logo:
    icon: /icons/lemisieur_round.png

- greeting:
    text_size: xl
    text: HomeLab

- datetime:
    text_size: xl
    format:
        timeStyle: short
        hour12: true